version: "2"

run:
    concurrency: 4
    tests: false

linters:
    enable:
        - bodyclose
        - exhaustive
        - goconst
        - godot
        - gomoddirectives
        - goprintffuncname
        - gosec
        - misspell
        - nakedret
        - nestif
        - nilerr
        - noctx
        - nolintlint
        - prealloc
        - rowserrcheck
        - sqlclosecheck
        - tparallel
        - unconvert
        - unparam
        - whitespace
        - wrapcheck
    settings:
        misspell:
            locale: US

formatters:
    enable:
        - gofmt
        - goimports
        - golines
    settings:
        gofmt:
            rewrite-rules:
                - pattern: "interface{}"
                  replacement: "any"
                - pattern: "a[b:len(a)]"
                  replacement: "a[b:]"
